import type { LessonQuiz } from "../../quiz/types";

/**
 * Climb (practice) and Summit (mastery) for "The unit circle and special angles".
 * Grounded in the lesson: on the unit circle a point is $(\cos\theta, \sin\theta)$,
 * cosine is the x-coordinate and sine is the y-coordinate, quadrant signs follow
 * the coordinate signs, $\cos^2\theta + \sin^2\theta = 1$ always, and the special
 * angles have exact coordinates from the 45-45-90 and 30-60-90 triangles.
 * Distractors are the classic traps: swapping sine and cosine, mixing up $\sqrt2/2$
 * with $\sqrt3/2$, misreading quadrant signs, and confusing an angle with its
 * coterminal partners.
 */
export const quiz: LessonQuiz = {
  climb: [
    {
      id: "c-unit",
      prompt: "The unit circle is the circle with:",
      choices: [
        { text: "radius $1$ centered at the origin", correct: true, explain: "A radius of exactly $1$ is what makes the coordinates read directly as cosine and sine." },
        { text: "radius $2$ centered at the origin", explain: "A radius of $2$ would scale the coordinates. The unit circle has radius $1$." },
        { text: "radius $1$ centered at $(1, 1)$", explain: "The center is the origin, not $(1, 1)$, so the terminal side sweeps from the center out." },
        { text: "diameter $1$ centered at the origin", explain: "It is the radius that equals $1$, not the diameter." },
      ],
    },
    {
      id: "c-standard",
      prompt: "An angle in standard position has:",
      choices: [
        { text: "its vertex at the origin and its initial side on the positive x-axis", correct: true, explain: "Standard position fixes where the angle starts, so its measure describes the rotation to the terminal side." },
        { text: "its vertex on the positive x-axis", explain: "The vertex sits at the origin, and the initial side lies along the positive x-axis." },
        { text: "its initial side on the positive y-axis", explain: "The initial side is the positive x-axis, not the y-axis." },
        { text: "its terminal side fixed at $90^\\circ$", explain: "The terminal side rotates freely. Only the vertex and initial side are fixed." },
      ],
    },
    {
      id: "c-positive",
      prompt: "A positive angle is generated by rotating:",
      choices: [
        { text: "counterclockwise from the positive x-axis", correct: true, explain: "Counterclockwise is the positive direction by convention." },
        { text: "clockwise from the positive x-axis", explain: "Clockwise rotation generates a negative angle." },
        { text: "clockwise from the positive y-axis", explain: "Rotation is measured from the positive x-axis, and counterclockwise is positive." },
        { text: "in either direction, the sign does not matter", explain: "Direction sets the sign: counterclockwise is positive, clockwise is negative." },
      ],
    },
    {
      id: "c-coterminal",
      prompt: "Which angle is coterminal with $45^\\circ$?",
      choices: [
        { text: "$405^\\circ$", correct: true, explain: "$405^\\circ = 45^\\circ + 360^\\circ$, so it shares the same terminal side." },
        { text: "$135^\\circ$", explain: "$135^\\circ$ points into Quadrant II, a different terminal side from $45^\\circ$." },
        { text: "$225^\\circ$", explain: "$225^\\circ$ is the opposite ray, in Quadrant III, not coterminal with $45^\\circ$." },
        { text: "$90^\\circ$", explain: "Coterminal angles differ by a full $360^\\circ$, so $405^\\circ$ works, not $90^\\circ$." },
      ],
    },
    {
      id: "c-cos-x",
      prompt: "For a point $P(x, y)$ where the terminal side meets the unit circle, $\\cos\\theta$ equals:",
      choices: [
        { text: "the x-coordinate", correct: true, explain: "On the unit circle $\\cos\\theta = x$ directly, because the radius is $1$." },
        { text: "the y-coordinate", explain: "The y-coordinate is $\\sin\\theta$. Cosine is the x-coordinate." },
        { text: "the ratio $\\tfrac{y}{x}$", explain: "That ratio is $\\tan\\theta$. Cosine is simply the x-coordinate here." },
        { text: "the distance from the origin", explain: "That distance is the radius $1$. Cosine is the x-coordinate of the point." },
      ],
    },
    {
      id: "c-sin-y",
      prompt: "On the unit circle, $\\sin\\theta$ equals:",
      choices: [
        { text: "the y-coordinate of the point", correct: true, explain: "Since the radius is $1$, the height of the point is exactly $\\sin\\theta$." },
        { text: "the x-coordinate of the point", explain: "The x-coordinate is $\\cos\\theta$. Sine is the height, the y-coordinate." },
        { text: "the slope of the terminal side", explain: "The slope is $\\tan\\theta$. Sine is the y-coordinate of the point." },
        { text: "always positive", explain: "Sine is negative below the x-axis. It equals the y-coordinate, which can be negative." },
      ],
    },
    {
      id: "c-q2",
      prompt: "In Quadrant II, the signs of cosine and sine are:",
      choices: [
        { text: "$\\cos\\theta < 0$ and $\\sin\\theta > 0$", correct: true, explain: "Quadrant II points have negative x and positive y, matching cosine and sine." },
        { text: "$\\cos\\theta > 0$ and $\\sin\\theta > 0$", explain: "Both positive is Quadrant I. In Quadrant II the x-coordinate is negative." },
        { text: "$\\cos\\theta < 0$ and $\\sin\\theta < 0$", explain: "Both negative is Quadrant III. In Quadrant II the y-coordinate is positive." },
        { text: "$\\cos\\theta > 0$ and $\\sin\\theta < 0$", explain: "That is Quadrant IV. Quadrant II has negative cosine and positive sine." },
      ],
    },
    {
      id: "c-q3",
      prompt: "For an angle whose terminal side lies in Quadrant III:",
      choices: [
        { text: "both $\\cos\\theta$ and $\\sin\\theta$ are negative", correct: true, explain: "Quadrant III points have negative x and negative y." },
        { text: "both are positive", explain: "Both positive is Quadrant I, not III." },
        { text: "cosine is positive, sine is negative", explain: "That describes Quadrant IV. In Quadrant III both are negative." },
        { text: "cosine is negative, sine is positive", explain: "That is Quadrant II. In Quadrant III both coordinates are negative." },
      ],
    },
    {
      id: "c-cos60",
      prompt: "What is $\\cos 60^\\circ$?",
      choices: [
        { text: "$\\tfrac12$", correct: true, explain: "At $60^\\circ$ the base (x-coordinate) is the short leg of the 30-60-90 triangle, $\\tfrac12$." },
        { text: "$\\tfrac{\\sqrt3}{2}$", explain: "That is $\\sin 60^\\circ$, the height. The base $\\cos 60^\\circ$ is $\\tfrac12$." },
        { text: "$\\tfrac{\\sqrt2}{2}$", explain: "That is the value at $45^\\circ$. At $60^\\circ$, cosine is $\\tfrac12$." },
        { text: "$1$", explain: "Cosine is $1$ only at $0^\\circ$. At $60^\\circ$ it is $\\tfrac12$." },
      ],
    },
    {
      id: "c-point45",
      prompt: "The point on the unit circle at $45^\\circ$ is:",
      choices: [
        { text: "$\\left(\\tfrac{\\sqrt2}{2}, \\tfrac{\\sqrt2}{2}\\right)$", correct: true, explain: "Equal legs give $\\cos 45^\\circ = \\sin 45^\\circ = \\tfrac{\\sqrt2}{2}$." },
        { text: "$\\left(\\tfrac12, \\tfrac{\\sqrt3}{2}\\right)$", explain: "That is the $60^\\circ$ point. At $45^\\circ$ the two coordinates are equal." },
        { text: "$\\left(\\tfrac{\\sqrt3}{2}, \\tfrac12\\right)$", explain: "That is the $30^\\circ$ point. At $45^\\circ$ both coordinates equal $\\tfrac{\\sqrt2}{2}$." },
        { text: "$\\left(1, 1\\right)$", explain: "That point is off the unit circle. The $45^\\circ$ point is $\\left(\\tfrac{\\sqrt2}{2}, \\tfrac{\\sqrt2}{2}\\right)$." },
      ],
    },
    {
      id: "c-sin30",
      prompt: "What is $\\sin 30^\\circ$?",
      choices: [
        { text: "$\\tfrac12$", correct: true, explain: "At $30^\\circ$ the height is the short leg of the 30-60-90 triangle, $\\tfrac12$." },
        { text: "$\\tfrac{\\sqrt3}{2}$", explain: "That is $\\cos 30^\\circ$. The height $\\sin 30^\\circ$ is $\\tfrac12$." },
        { text: "$\\tfrac{\\sqrt2}{2}$", explain: "That is the $45^\\circ$ value. At $30^\\circ$, sine is $\\tfrac12$." },
        { text: "$0$", explain: "Sine is $0$ at $0^\\circ$. At $30^\\circ$ it is $\\tfrac12$." },
      ],
    },
    {
      id: "c-pythag",
      prompt: "As the terminal side rotates, the value of $\\cos^2\\theta + \\sin^2\\theta$:",
      choices: [
        { text: "stays equal to $1$", correct: true, explain: "The point never leaves a circle of radius $1$, so $x^2 + y^2 = 1$ always." },
        { text: "grows toward $2$", explain: "The sum is fixed at $1$ for every angle, so it never grows." },
        { text: "depends on the quadrant", explain: "Signs change, but the squares are always non-negative and sum to $1$ everywhere." },
        { text: "equals $0$ at $90^\\circ$", explain: "At $90^\\circ$, $\\cos^2 + \\sin^2 = 0 + 1 = 1$, like everywhere else." },
      ],
    },
    {
      id: "c-solve-sin",
      prompt: "If $\\cos\\theta = \\tfrac35$ and $\\theta$ is in Quadrant I, then $\\sin\\theta$ equals:",
      choices: [
        { text: "$\\tfrac45$", correct: true, explain: "$\\sin^2\\theta = 1 - \\tfrac{9}{25} = \\tfrac{16}{25}$, and sine is positive in Quadrant I, so $\\sin\\theta = \\tfrac45$." },
        { text: "$\\tfrac25$", explain: "That does not satisfy $\\cos^2 + \\sin^2 = 1$. The correct value is $\\tfrac45$." },
        { text: "$\\tfrac53$", explain: "Sine can never exceed $1$. From the identity, $\\sin\\theta = \\tfrac45$." },
        { text: "$-\\tfrac45$", explain: "In Quadrant I sine is positive, so $\\sin\\theta = +\\tfrac45$." },
      ],
    },
    {
      id: "c-opposite-leg",
      prompt: "In the right triangle inside the unit circle, the leg opposite the acute angle $\\theta$ has length:",
      choices: [
        { text: "$\\sin\\theta$", correct: true, explain: "The opposite leg is vertical, and its length is the y-coordinate, $\\sin\\theta$." },
        { text: "$\\cos\\theta$", explain: "The adjacent (horizontal) leg is $\\cos\\theta$. The opposite leg is $\\sin\\theta$." },
        { text: "$1$", explain: "The hypotenuse is $1$, the radius. The opposite leg is $\\sin\\theta$." },
        { text: "$\\tan\\theta$", explain: "That is a ratio of legs. The opposite leg itself has length $\\sin\\theta$." },
      ],
    },
    {
      id: "c-sin180",
      prompt: "What is $\\sin 180^\\circ$?",
      choices: [
        { text: "$0$", correct: true, explain: "At $180^\\circ$ the point sits at $(-1, 0)$, so its height is $0$." },
        { text: "$1$", explain: "Sine reaches $1$ at $90^\\circ$. At $180^\\circ$ the height is $0$." },
        { text: "$-1$", explain: "Sine is $-1$ at $270^\\circ$. At $180^\\circ$ it is $0$." },
        { text: "$\\tfrac12$", explain: "The point at $180^\\circ$ is $(-1, 0)$, so $\\sin 180^\\circ = 0$." },
      ],
    },
  ],
  summit: [
    {
      id: "s-coterminal-neg",
      prompt: "Which angle is coterminal with $60^\\circ$?",
      choices: [
        { text: "$-300^\\circ$", correct: true, explain: "$-300^\\circ + 360^\\circ = 60^\\circ$, so they share a terminal side." },
        { text: "$-60^\\circ$", explain: "$-60^\\circ$ lands in Quadrant IV, the reflection of $60^\\circ$, not coterminal." },
        { text: "$120^\\circ$", explain: "$120^\\circ$ is a different terminal side in Quadrant II." },
        { text: "$300^\\circ$", explain: "$300^\\circ$ is in Quadrant IV, not coterminal with $60^\\circ$." },
      ],
    },
    {
      id: "s-quad-signs",
      prompt: "In which quadrant is $\\sin\\theta > 0$ while $\\cos\\theta < 0$?",
      choices: [
        { text: "Quadrant II", correct: true, explain: "Negative x with positive y is Quadrant II, so cosine is negative and sine positive." },
        { text: "Quadrant I", explain: "In Quadrant I both are positive." },
        { text: "Quadrant III", explain: "In Quadrant III both are negative." },
        { text: "Quadrant IV", explain: "In Quadrant IV cosine is positive and sine negative, the reverse." },
      ],
    },
    {
      id: "s-cos30",
      prompt: "What is $\\cos 30^\\circ$?",
      choices: [
        { text: "$\\tfrac{\\sqrt3}{2}$", correct: true, explain: "At $30^\\circ$ the base is the long leg of the 30-60-90 triangle, $\\tfrac{\\sqrt3}{2}$." },
        { text: "$\\tfrac12$", explain: "That is $\\sin 30^\\circ$, the height. The base $\\cos 30^\\circ$ is $\\tfrac{\\sqrt3}{2}$." },
        { text: "$\\tfrac{\\sqrt2}{2}$", explain: "That is the $45^\\circ$ value. At $30^\\circ$, cosine is $\\tfrac{\\sqrt3}{2}$." },
        { text: "$\\tfrac{\\sqrt3}{3}$", explain: "That is a different quantity. On the unit circle $\\cos 30^\\circ = \\tfrac{\\sqrt3}{2}$." },
      ],
    },
    {
      id: "s-point30",
      prompt: "The point on the unit circle at $30^\\circ$ is:",
      choices: [
        { text: "$\\left(\\tfrac{\\sqrt3}{2}, \\tfrac12\\right)$", correct: true, explain: "The base is $\\cos 30^\\circ = \\tfrac{\\sqrt3}{2}$ and the height is $\\sin 30^\\circ = \\tfrac12$." },
        { text: "$\\left(\\tfrac12, \\tfrac{\\sqrt3}{2}\\right)$", explain: "That swaps the coordinates. It is the $60^\\circ$ point, not $30^\\circ$." },
        { text: "$\\left(\\tfrac{\\sqrt2}{2}, \\tfrac{\\sqrt2}{2}\\right)$", explain: "Equal coordinates occur at $45^\\circ$, not $30^\\circ$." },
        { text: "$\\left(\\tfrac12, \\tfrac12\\right)$", explain: "That point is not on the unit circle. At $30^\\circ$ it is $\\left(\\tfrac{\\sqrt3}{2}, \\tfrac12\\right)$." },
      ],
    },
    {
      id: "s-swap",
      prompt: "Why do the coordinates at $30^\\circ$ and $60^\\circ$ swap, giving $\\left(\\tfrac{\\sqrt3}{2}, \\tfrac12\\right)$ and $\\left(\\tfrac12, \\tfrac{\\sqrt3}{2}\\right)$?",
      choices: [
        { text: "the short leg always faces the smaller angle, so the roles of base and height trade", correct: true, explain: "The $30^\\circ$ and $60^\\circ$ triangles are the same shape reflected, so the short leg $\\tfrac12$ is the height at $30^\\circ$ and the base at $60^\\circ$." },
        { text: "sine and cosine are always equal", explain: "They are equal only at $45^\\circ$. Here they swap values between the two angles." },
        { text: "the radius changes between them", explain: "The radius stays $1$. Only which leg is base versus height changes." },
        { text: "the angles are coterminal", explain: "$30^\\circ$ and $60^\\circ$ are different terminal sides, not coterminal. The legs simply trade roles." },
      ],
    },
    {
      id: "s-solve-q3",
      prompt: "If $\\cos\\theta = -0.6$ and $\\theta$ is in Quadrant III, then $\\sin\\theta$ equals:",
      choices: [
        { text: "$-0.8$", correct: true, explain: "$\\sin^2\\theta = 1 - 0.36 = 0.64$, and sine is negative in Quadrant III, so $\\sin\\theta = -0.8$." },
        { text: "$0.8$", explain: "The size is $0.8$, but sine is negative in Quadrant III, so $\\sin\\theta = -0.8$." },
        { text: "$-0.4$", explain: "That does not satisfy the identity. $\\sin^2 = 0.64$ gives $|\\sin| = 0.8$." },
        { text: "$-0.36$", explain: "That is $\\sin^2$ misread. Take the square root: $\\sin\\theta = -0.8$." },
      ],
    },
    {
      id: "s-270",
      prompt: "What are the coordinates of the point at $270^\\circ$?",
      choices: [
        { text: "$(0, -1)$", correct: true, explain: "At $270^\\circ$ the terminal side points straight down, so $\\cos = 0$ and $\\sin = -1$." },
        { text: "$(0, 1)$", explain: "That is $90^\\circ$, pointing straight up. $270^\\circ$ points down to $(0, -1)$." },
        { text: "$(-1, 0)$", explain: "That is $180^\\circ$. At $270^\\circ$ the point is $(0, -1)$." },
        { text: "$(1, 0)$", explain: "That is $0^\\circ$. At $270^\\circ$ the point is $(0, -1)$." },
      ],
    },
    {
      id: "s-cos90",
      prompt: "What is $\\cos 90^\\circ$?",
      choices: [
        { text: "$0$", correct: true, explain: "At $90^\\circ$ the point is $(0, 1)$, so its x-coordinate $\\cos 90^\\circ$ is $0$." },
        { text: "$1$", explain: "That is $\\sin 90^\\circ$, the height. The base $\\cos 90^\\circ$ is $0$." },
        { text: "$-1$", explain: "$\\cos 180^\\circ = -1$. At $90^\\circ$, cosine is $0$." },
        { text: "$\\tfrac{\\sqrt2}{2}$", explain: "That is the $45^\\circ$ value. At $90^\\circ$, cosine is $0$." },
      ],
    },
    {
      id: "s-q4",
      prompt: "In Quadrant IV, the signs are:",
      choices: [
        { text: "$\\cos\\theta > 0$ and $\\sin\\theta < 0$", correct: true, explain: "Quadrant IV points have positive x and negative y." },
        { text: "$\\cos\\theta < 0$ and $\\sin\\theta < 0$", explain: "Both negative is Quadrant III. In IV the x-coordinate is positive." },
        { text: "$\\cos\\theta > 0$ and $\\sin\\theta > 0$", explain: "Both positive is Quadrant I. In IV the y-coordinate is negative." },
        { text: "$\\cos\\theta < 0$ and $\\sin\\theta > 0$", explain: "That is Quadrant II. Quadrant IV has positive cosine and negative sine." },
      ],
    },
    {
      id: "s-coterminal-reduce",
      prompt: "Which angle between $0^\\circ$ and $360^\\circ$ is coterminal with $400^\\circ$?",
      choices: [
        { text: "$40^\\circ$", correct: true, explain: "$400^\\circ - 360^\\circ = 40^\\circ$, the same terminal side after removing one full turn." },
        { text: "$400^\\circ$", explain: "That is not between $0^\\circ$ and $360^\\circ$. Subtract $360^\\circ$ to get $40^\\circ$." },
        { text: "$140^\\circ$", explain: "That subtracts $260^\\circ$, not a full turn. The coterminal angle is $40^\\circ$." },
        { text: "$320^\\circ$", explain: "That would come from $-40^\\circ$. Here $400^\\circ - 360^\\circ = 40^\\circ$." },
      ],
    },
    {
      id: "s-point-to-angle",
      prompt: "A terminal side meets the unit circle at $\\left(-\\tfrac{\\sqrt2}{2}, \\tfrac{\\sqrt2}{2}\\right)$. The angle is:",
      choices: [
        { text: "$135^\\circ$", correct: true, explain: "Equal magnitudes $\\tfrac{\\sqrt2}{2}$ with negative x and positive y put the point in Quadrant II at $135^\\circ$." },
        { text: "$45^\\circ$", explain: "$45^\\circ$ has both coordinates positive. The negative x here means Quadrant II, $135^\\circ$." },
        { text: "$225^\\circ$", explain: "$225^\\circ$ has both coordinates negative. Here y is positive, so it is $135^\\circ$." },
        { text: "$315^\\circ$", explain: "$315^\\circ$ has positive x and negative y. This point is $135^\\circ$." },
      ],
    },
    {
      id: "s-identity-q2",
      prompt: "If $\\sin\\theta = \\tfrac{12}{13}$ and $\\theta$ is in Quadrant II, then $\\cos\\theta$ equals:",
      choices: [
        { text: "$-\\tfrac{5}{13}$", correct: true, explain: "$\\cos^2\\theta = 1 - \\tfrac{144}{169} = \\tfrac{25}{169}$, and cosine is negative in Quadrant II, so $\\cos\\theta = -\\tfrac{5}{13}$." },
        { text: "$\\tfrac{5}{13}$", explain: "The size is $\\tfrac{5}{13}$, but cosine is negative in Quadrant II, so it is $-\\tfrac{5}{13}$." },
        { text: "$-\\tfrac{1}{13}$", explain: "That does not satisfy the identity. $\\cos^2 = \\tfrac{25}{169}$ gives $|\\cos| = \\tfrac{5}{13}$." },
        { text: "$-\\tfrac{12}{13}$", explain: "That repeats the sine value. Using the identity, $\\cos\\theta = -\\tfrac{5}{13}$." },
      ],
    },
    {
      id: "s-max-sin",
      prompt: "Over one full turn, $\\sin\\theta$ reaches its maximum value of $1$ at:",
      choices: [
        { text: "$90^\\circ$", correct: true, explain: "The y-coordinate is largest at the very top of the circle, which is $90^\\circ$." },
        { text: "$0^\\circ$", explain: "At $0^\\circ$ the height is $0$. The maximum height is at $90^\\circ$." },
        { text: "$180^\\circ$", explain: "At $180^\\circ$ the height is $0$ again. Sine peaks at $90^\\circ$." },
        { text: "$270^\\circ$", explain: "At $270^\\circ$ sine is at its minimum $-1$. The maximum is at $90^\\circ$." },
      ],
    },
    {
      id: "s-period",
      prompt: "The sine and cosine graphs are periodic with period $360^\\circ$ because:",
      choices: [
        { text: "the terminal side returns to the same position after one full rotation", correct: true, explain: "After $360^\\circ$ the point is back where it started, so the coordinates and their function values repeat." },
        { text: "the radius grows each turn", explain: "The radius stays $1$. Periodicity comes from the terminal side returning after a full turn." },
        { text: "sine and cosine are equal", explain: "They are equal only at special angles. The period reflects the full rotation repeating." },
        { text: "the graphs are straight lines", explain: "They are waves, not lines, and they repeat every $360^\\circ$." },
      ],
    },
    {
      id: "s-tan-undef",
      prompt: "Using $\\cos^2\\theta + \\sin^2\\theta = 1$, what is $\\sin\\theta$ if $\\cos\\theta = 1$?",
      choices: [
        { text: "$0$", correct: true, explain: "$\\sin^2\\theta = 1 - 1 = 0$, so $\\sin\\theta = 0$. This is the point $(1, 0)$ at $0^\\circ$." },
        { text: "$1$", explain: "If sine were $1$ the sum would be $2$, not $1$. Here $\\sin\\theta = 0$." },
        { text: "$-1$", explain: "The identity forces $\\sin^2 = 0$, so $\\sin\\theta = 0$, not $-1$." },
        { text: "$\\tfrac12$", explain: "Then the sum would exceed $1$. With $\\cos\\theta = 1$, $\\sin\\theta = 0$." },
      ],
    },
  ],
};
