import type { Overlays } from "../../components/UnitCircleFigure";
import { toRadians } from "../../lib/trig";
import type { Control, Slide } from "../types";

const base: Overlays = {
  angleArc: true,
  angleLabel: false,
  sideLabels: false,
  coords: false,
  legs: false,
  wedge: false,
  triangleLabels: false,
  identityBar: false,
  waves: false,
};

const degrees: Control = {
  label: "Angle",
  step: 5,
  format: (value) => `${Math.round(value)}°`,
};

export const slides: Slide[] = [
  {
    id: "standard-position",
    title: "What does it mean for an angle to be in standard position?",
    mode: "angle",
    start: 0,
    range: [-1440, 1440],
    control: degrees,
    baseReveal: { ...base, angleLabel: true },
    beats: [
      {
        text: "The **unit circle** is the circle of radius 1 centered at the origin.",
      },
      {
        text: "An angle is in **standard position** when its vertex is at the origin and its **initial side** lies along the positive x-axis. The ray that rotates away from it is the **terminal side**.",
        to: 55,
        ms: 1900,
        add: { sideLabels: true },
      },
      {
        text: "A **positive angle** is generated by a counterclockwise rotation.",
        to: 135,
        ms: 1700,
      },
      {
        text: "A **negative angle** is generated by a clockwise rotation.",
        to: -120,
        ms: 2400,
      },
      {
        text: "Because the terminal side may rotate more than once, angle measures are not limited to a single turn.",
        to: 430,
        ms: 2800,
      },
    ],
    practice: "Rotate the terminal side and watch the angle grow past a full turn.",
    questions: [
      {
        kind: "manipulate",
        prompt: "Rotate the terminal side until the total rotation passes 1000°.",
        hint: "Keep turning in one direction. Every complete turn adds another 360°.",
        success:
          "Two full turns is 720° and three is 1080°, so a measure past 1000° is an ordinary angle in standard position.",
        check: (angle) => Math.abs(angle) >= 1000,
      },
      {
        kind: "choice",
        prompt:
          "Angles in standard position that share a terminal side are called coterminal. Which angle is coterminal with 45°?",
        options: ["135°", "225°", "405°"],
        answer: 2,
        hint: "Add one full rotation of 360° to 45°.",
        success: "405° = 45° + 360°, so the two angles have exactly the same terminal side.",
      },
      {
        kind: "choice",
        prompt: "A clockwise rotation from the positive x-axis generates",
        options: ["a positive angle", "a negative angle", "an angle of 0°"],
        answer: 1,
        hint: "Counterclockwise is the positive direction.",
        success: "Clockwise rotation generates a negative angle. Counterclockwise generates a positive angle.",
      },
    ],
  },
  {
    id: "sine-cosine",
    title: "How do we read sine and cosine from a point on the unit circle?",
    mode: "coords",
    start: 0,
    range: [-720, 720],
    control: degrees,
    baseReveal: { ...base, angleLabel: true },
    beats: [
      {
        text: "Let θ be an angle in standard position, and let P(x, y) be the point where the terminal side intersects the unit circle.",
        to: 50,
        ms: 1700,
        add: { coords: true },
      },
      {
        text: "By definition, **cos θ = x** and **sin θ = y**. Because the radius is 1, the coordinates of P give the function values directly, with no division.",
        draw: true,
        ms: 1500,
        add: { legs: true },
      },
      {
        text: "In **Quadrant II** the x coordinate is negative, so cosine is negative while sine remains positive.",
        to: 145,
        ms: 1800,
        add: { wedge: true },
      },
      {
        text: "In **Quadrant III** both coordinates are negative, so sine and cosine are both negative.",
        to: 215,
        ms: 1600,
      },
      {
        text: "In **Quadrant IV** the x coordinate is positive again while the y coordinate stays negative.",
        to: 315,
        ms: 1600,
      },
    ],
    practice: "Move the point and watch both coordinates change sign.",
    questions: [
      {
        kind: "manipulate",
        prompt: "Place the terminal side so that cos θ < 0 and sin θ > 0.",
        hint: "Cosine is the x coordinate, so look left of the y-axis and above the x-axis.",
        success: "That is Quadrant II, where the x coordinate is negative and the y coordinate is positive.",
        check: (angle) => Math.cos(toRadians(angle)) < -0.05 && Math.sin(toRadians(angle)) > 0.05,
      },
      {
        kind: "choice",
        prompt: "For an angle whose terminal side lies in Quadrant III, which statement is true?",
        options: ["sin θ > 0 and cos θ > 0", "sin θ < 0 and cos θ < 0", "sin θ > 0 and cos θ < 0"],
        answer: 1,
        hint: "In Quadrant III, both coordinates of the point are negative.",
        success: "Both coordinates are negative in Quadrant III, so sine and cosine are both negative there.",
      },
    ],
  },
  {
    id: "pythagorean-identity",
    title: "Why does cos²θ + sin²θ equal 1 for every angle?",
    mode: "identity",
    start: 40,
    range: [-720, 720],
    control: degrees,
    baseReveal: { ...base },
    beats: [
      {
        text: "Every point (x, y) on the unit circle satisfies the equation x² + y² = 1.",
        add: { coords: true, legs: true },
      },
      {
        text: "Substituting x = cos θ and y = sin θ produces the **Pythagorean identity**, cos²θ + sin²θ = 1.",
        to: 130,
        ms: 1900,
        add: { identityBar: true },
      },
      {
        text: "An **identity** holds for every value of the variable, so the sum stays equal to 1 in every quadrant.",
        to: 400,
        ms: 3000,
      },
    ],
    practice: "Rotate the point and watch the two squares trade size while the sum holds.",
    questions: [
      {
        kind: "choice",
        prompt: "As the terminal side rotates, the value of cos²θ + sin²θ",
        options: ["grows toward 2", "stays equal to 1", "depends on the quadrant"],
        answer: 1,
        hint: "The point never leaves a circle of radius 1.",
        success: "The point always lies on the unit circle, so the sum of the squares is always 1.",
      },
      {
        kind: "choice",
        prompt: "If cos θ = 3/5 and θ is a first quadrant angle, then sin θ =",
        options: ["2/5", "4/5", "5/3"],
        answer: 1,
        hint: "Substitute into cos²θ + sin²θ = 1 and solve for sin θ.",
        success: "sin²θ = 1 − 9/25 = 16/25, and sine is positive in Quadrant I, so sin θ = 4/5.",
      },
    ],
  },
  {
    id: "right-triangle",
    title: "How does a right triangle sit inside the unit circle?",
    mode: "triangle",
    start: 40,
    range: [0, 90],
    control: degrees,
    baseReveal: { ...base },
    beats: [
      {
        text: "Drop a perpendicular from P to the x-axis. With the radius, it forms a right triangle whose acute angle at the origin is θ.",
        draw: true,
        ms: 1600,
        add: { legs: true },
      },
      {
        text: "The hypotenuse is a radius of the unit circle, so its length is **1**. The horizontal leg has length **cos θ**, and the vertical leg has length **sin θ**.",
        to: 62,
        ms: 1800,
        add: { triangleLabels: true },
      },
      {
        text: "This agrees with the right triangle definitions sin θ = opposite / hypotenuse and cos θ = adjacent / hypotenuse, because dividing by 1 leaves the lengths unchanged.",
      },
    ],
    practice: "Drag inside the first quadrant. Rotation is restricted here to 0° through 90°.",
    questions: [
      {
        kind: "choice",
        prompt: "In this triangle, the leg opposite θ has length",
        options: ["cos θ", "sin θ", "1"],
        answer: 1,
        hint: "The opposite leg is the vertical one. Which coordinate gives its length?",
        success: "The opposite leg is vertical, and its length is the y coordinate of P, which is sin θ.",
      },
      {
        kind: "choice",
        prompt: "If cos θ = 0.6 for an acute angle θ, then sin θ =",
        options: ["0.4", "0.8", "1.2"],
        answer: 1,
        hint: "Use 0.6² + sin²θ = 1.",
        success: "sin²θ = 1 − 0.36 = 0.64, so sin θ = 0.8. This is the 3, 4, 5 right triangle scaled by one fifth.",
      },
    ],
  },
  {
    id: "graphs",
    title: "How does the unit circle become the graphs of sine and cosine?",
    mode: "wave",
    start: 0,
    range: [-720, 1440],
    control: degrees,
    baseReveal: { ...base, angleLabel: true },
    beats: [
      {
        text: "To graph the sine function, plot the angle θ on the horizontal axis and the value sin θ on the vertical axis.",
        to: 90,
        ms: 1600,
        add: { waves: true, legs: true },
      },
      {
        text: "As the terminal side rotates, the height of the point traces out the curve.",
        to: 360,
        ms: 2600,
      },
      {
        text: "Cosine traces the same shape, shifted along the axis.",
        to: 540,
        ms: 2000,
      },
      {
        text: "Both graphs are **periodic** with period 360°, or 2π radians, because the terminal side returns to its position after one full rotation.",
        to: 720,
        ms: 2200,
      },
    ],
    practice: "Rotate in either direction. Turning clockwise runs the graphs backward.",
    questions: [
      {
        kind: "choice",
        prompt: "At θ = 180°, sin θ =",
        options: ["1", "0", "−1"],
        answer: 1,
        hint: "At 180° the point sits on the negative x-axis. What is its height?",
        success: "At 180° the point is (−1, 0), so its y coordinate, sin θ, equals 0.",
      },
      {
        kind: "manipulate",
        prompt: "Rotate until sin θ reaches its maximum value of 1.",
        hint: "The y coordinate is largest at the very top of the circle.",
        success: "sin θ = 1 at 90°, and again at 450°, and at every angle coterminal with 90°.",
        check: (angle) => Math.sin(toRadians(angle)) > 0.995,
      },
    ],
  },
];
